### ISSUE TITLE
Test SEND-BUFFERED hangs

### ISSUE THREAD

**Issue by viliaapro** [zkat/chanl#24]
Hello, I just installed ChanL from Quicklisp, did the tests, and it hung on `SEND-BUFFERED`. The others went OK, it seems, after interrupting and somehow nudging the tests forward from SLIME.

I'm using SBCL 2.3.0 on a x86_64 GNU/Linux.

All I got from the debugger after interrupting the test was `("bogus stack frame")` .

Here's some more info from SLIME; I'm not sure if the circularity is related in any way to `SEND-BUFFERED`, or just a coincidence; anyway it seems `SEND-BUFFERED` was `SENDING`.

`WARNING:
   Deprecated recursive use of (ASDF/OPERATE:OPERATE 'ASDF/LISP-ACTION:TEST-OP
   '("chanl")) while visiting (ASDF/LISP-ACTION:TEST-OP "chanl/tests") - please
   use proper dependencies instead`

` Failure Details:
  SEND-BUFFERED in SENDING []: 
      Unexpected Error: #<ASDF/ACTION:CIRCULAR-DEPENDENCY {100652A163}>
Circular dependency:
   ((#<ASDF/LISP-ACTION:TEST-OP > . #<ASDF/SYSTEM:SYSTEM "chanl/tests">)
    (#<ASDF/LISP-ACTION:TEST-OP > . #<ASDF/SYSTEM:SYSTEM "chanl">)).`

**Comment by adlai** [comment]
> I'm using SBCL 2.3.0 on a x86_64 GNU/Linux.
> 
> All I got from the debugger after interrupting the test was `("bogus stack frame")` .
> 
> Here's some more info from SLIME; I'm not sure if the circularity is related in any way to `SEND-BUFFERED`, or just a coincidence; anyway it seems `SEND-BUFFERED` was `SENDING`.
> 
> `WARNING: Deprecated recursive use of (ASDF/OPERATE:OPERATE 'ASDF/LISP-ACTION:TEST-OP '("chanl")) while visiting (ASDF/LISP-ACTION:TEST-OP "chanl/tests") - please use proper dependencies instead`

The test suite was written long ago, before XCVB etc...

Do you have any customisations, whatsoever, on your system?

**Comment by viliaapro** [comment]
No, I don't have any customisations; the SBCL was compiled from source with the SBCL that comes with Debian.

Tue, 17 Jan 2023 01:05:19 -0800
Adlai ***@***.***> kirjoitti:

> > I'm using SBCL 2.3.0 on a x86_64 GNU/Linux.
> > 
> > All I got from the debugger after interrupting the test was `("bogus stack frame")` .
> > 
> > Here's some more info from SLIME; I'm not sure if the circularity is related in any way to `SEND-BUFFERED`, or just a coincidence; anyway it seems `SEND-BUFFERED` was `SENDING`.
> > 
> > `WARNING: Deprecated recursive use of (ASDF/OPERATE:OPERATE 'ASDF/LISP-ACTION:TEST-OP '("chanl")) while visiting (ASDF/LISP-ACTION:TEST-OP "chanl/tests") - please use proper dependencies instead`  
> 
> The test suite was written long ago, before XCVB etc...
> 
> Do you have any customisations, whatsoever, on your system?
>

**Comment by adlai** [comment]
What invocation did you use to begin the ASDF operations?

**Comment by viliaapro** [comment]
I did `(asdf:oos 'asdf:test-op 'chanl)`, and also `(asdf:oos 'asdf:test-op 'chanl/tests)`, after commenting out line 24 in `chanl.asd` to see if the circularity was to blame; it didn't stop the hanging up.

**Comment by viliaapro** [comment]
Ok, I tried `(run-all-tests)`. I hangs at the same spot; here's some backtrace.

` 0: ("bogus stack frame")
  1: ((FLET SB-UNIX::BODY :IN SB-THREAD::FUTEX-WAIT))
  2: ((FLET "WITHOUT-INTERRUPTS-BODY-2" :IN SB-THREAD::%CONDITION-WAIT))
  3: (SB-THREAD:CONDITION-WAIT #<SB-THREAD:WAITQUEUE Anonymous condition variable {100323A673}> #<SB-THREAD:MUTEX "Anonymous recursive lock" free owner=0> :TIMEOUT NIL)
  4: (BORDEAUX-THREADS:CONDITION-WAIT #<SB-THREAD:WAITQUEUE Anonymous condition variable {100323A673}> #<SB-THREAD:MUTEX "Anonymous recursive lock" free owner=0> :TIMEOUT NIL)
  5: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN CHANL:SEND))
  6: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
  7: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<FUNCTION (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN CHANL:SEND) {7F64D6C6D3CB}> #<SB-THREAD:MUTEX "Anonymous recursive lock" free owner=0> T NIL)
  8: ((:METHOD CHANL:SEND (CHANL:CHANNEL T)) #<CHANL:BOUNDED-CHANNEL [0/1] {1003213E83}> CHANL::TEST :BLOCKP T) [fast-method]`

**Comment by adlai** [comment]
Your code formatting is borked. I'm attempting to edit this myself, for the benefit of anyone reading on the website; I am not optimistic about my chances to get this correct.

However, thank you for the report; that is indeed a chanl bug. What is the multiprocessing configuration of the machine that barfed this backtrace?

**Comment by viliaapro** [comment]
Apparently email replies in Github don't support Markdown.

I'm running a vanilla Linux Mint 21.1, haven't touched any knobs.

CPU: dual core Intel Core i5-4310M (-MT MCP-)
Kernel: 5.15.0-56-generic x86_64

**Comment by adlai** [comment]
On 1/19/23, viliaapro ***@***.***> wrote:
> Apparently email replies in Github don't support Markdown.

Electronic mail is worse than the brain cancer of cellular phones.

>
> I'm running a vanilla Linux Mint 21.1, haven't touched any knobs.
>
> CPU: dual core Intel Core i5-4310M (-MT MCP-)
> Kernel: 5.15.0-56-generic x86_64

My interpretation of this information is that there's no chance that
any operating system magic of simulated multiprocessing has caused the
race condition to occur.

Again, thank you for reporting the failure; do you wish additional
notification after I have improved the granularity of information
reported in the backtraces?

**Comment by viliaapro** [comment]
No pressure from side; I was just casually checking out different CL libraries from Quicklisp. And your interpretation as to virtualisation is correct, I'm not using any such.

Report your findings on this Issue as you find fit. And do take a break, a month or two sweeping floors in an ashram or whatever.
