### ISSUE TITLE
Debugger invoked on a TYPE-ERROR in thread

### ISSUE THREAD

**Issue by cmpitg** [zkat/chanl#6]
Hi,

With `chanl-20150302-git` and SBCL 1.2.9, installed from Quicklisp, I encounter the following errors:

```
* (ql:quickload "chanl")
To load "chanl":
  Load 1 ASDF system:
    chanl
; Loading "chanl"

("chanl")
* (use-package :chanl)

T
* (defun recv-message (chan) (pcall #'(lambda () (format t "~A~%" (recv chan)))))
RECV-MESSAGE
* (defvar *c* (make-instance 'channel))

*C*
* (recv-message *c*)

#<TASK Anonymous task [ALIVE] {100583C213}>
* 
debugger invoked on a TYPE-ERROR in thread
#<THREAD "ChanL Thread Pool Worker" RUNNING {100583E093}>:
  The value -2 is not of type LIST.
```

I have tried to revert back to several recent commits and re-installed it but the error still persisted. Does anyone have idea on this matter?  What could possibly be the problem?

**Comment by adlai** [comment]
Couldn't reproduce this on 1.2.6 or 1.2.8, started a build of 1.2.9 to check that version.

Can you post a backtrace? Also, please try running the unit tests.
