### ISSUE TITLE
Test Failures on LispWorks 7 OS X 64-bit

### ISSUE THREAD

**Issue by aamedina** [zkat/chanl#9]
Failure Details:

---

 ACTORS-UNSANITY []: 
      Unexpected Error: #<SIMPLE-ERROR 4020107A33>
No method found: #<STANDARD-GENERIC-FUNCTION PERFORM 41E0173B44>,(SEND OUTPUT),(#:|actor4158|)...

---

---

 ACTORS-INSANITY []: 
      Unexpected Error: #<SIMPLE-ERROR 4020051283>
No method found: #<STANDARD-GENERIC-FUNCTION PERFORM 41E0173B44>,(SEND OUTPUT),(#:|actor4156|)...

---

**Comment by adlai** [comment]
Does this happen consistently? I've observed rare nondeterministic bugs with these, rare enough (and not occurring on production) that they've not yet merited isolation.

**Comment by adlai** [comment]
@aamedina (or anyone else):

If you'd like to help debug this platform, please reopen the issue.
